# Generated by Django 5.1.3 on 2024-11-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('vaccinated', models.BooleanField()),
                ('description', models.TextField()),
                ('species', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField()),
                ('age', models.IntegerField()),
                ('vaccinated', models.BooleanField()),
                ('description', models.TextField()),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('name', models.CharField()),
                ('vaccinated', models.BooleanField()),
                ('breed', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exotic_Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_of_origin', models.CharField()),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('type_of_animal', models.CharField()),
                ('vaccinated', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('age', models.IntegerField()),
                ('number_of_pets', models.IntegerField()),
            ],
        ),
    ]
